# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from ship_engine_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    V1_ACCOUNT_SETTINGS = "/v1/account/settings"
    V1_ACCOUNT_SETTINGS_IMAGES = "/v1/account/settings/images"
    V1_ACCOUNT_SETTINGS_IMAGES_LABEL_IMAGE_ID = "/v1/account/settings/images/{label_image_id}"
    V1_ADDRESSES_RECOGNIZE = "/v1/addresses/recognize"
    V1_ADDRESSES_VALIDATE = "/v1/addresses/validate"
    V1_BATCHES = "/v1/batches"
    V1_BATCHES_EXTERNAL_BATCH_ID_EXTERNAL_BATCH_ID = "/v1/batches/external_batch_id/{external_batch_id}"
    V1_BATCHES_BATCH_ID = "/v1/batches/{batch_id}"
    V1_BATCHES_BATCH_ID_ADD = "/v1/batches/{batch_id}/add"
    V1_BATCHES_BATCH_ID_ERRORS = "/v1/batches/{batch_id}/errors"
    V1_BATCHES_BATCH_ID_PROCESS_LABELS = "/v1/batches/{batch_id}/process/labels"
    V1_BATCHES_BATCH_ID_REMOVE = "/v1/batches/{batch_id}/remove"
    V1_CARRIERS = "/v1/carriers"
    V1_CARRIERS_CARRIER_ID = "/v1/carriers/{carrier_id}"
    V1_CARRIERS_CARRIER_ID_ADD_FUNDS = "/v1/carriers/{carrier_id}/add_funds"
    V1_CARRIERS_CARRIER_ID_OPTIONS = "/v1/carriers/{carrier_id}/options"
    V1_CARRIERS_CARRIER_ID_PACKAGES = "/v1/carriers/{carrier_id}/packages"
    V1_CARRIERS_CARRIER_ID_SERVICES = "/v1/carriers/{carrier_id}/services"
    V1_CONNECTIONS_CARRIERS_CARRIER_NAME = "/v1/connections/carriers/{carrier_name}"
    V1_CONNECTIONS_CARRIERS_CARRIER_NAME_CARRIER_ID = "/v1/connections/carriers/{carrier_name}/{carrier_id}"
    V1_CONNECTIONS_CARRIERS_CARRIER_NAME_CARRIER_ID_SETTINGS = "/v1/connections/carriers/{carrier_name}/{carrier_id}/settings"
    V1_CONNECTIONS_INSURANCE_SHIPSURANCE = "/v1/connections/insurance/shipsurance"
    V1_DOWNLOADS_DIR_SUBDIR_FILENAME = "/v1/downloads/{dir}/{subdir}/{filename}"
    V1_ENVIRONMENT_WEBHOOKS = "/v1/environment/webhooks"
    V1_ENVIRONMENT_WEBHOOKS_WEBHOOK_ID = "/v1/environment/webhooks/{webhook_id}"
    V1_INSURANCE_SHIPSURANCE_ADD_FUNDS = "/v1/insurance/shipsurance/add_funds"
    V1_INSURANCE_SHIPSURANCE_BALANCE = "/v1/insurance/shipsurance/balance"
    V1_LABELS = "/v1/labels"
    V1_LABELS_EXTERNAL_SHIPMENT_ID_EXTERNAL_SHIPMENT_ID = "/v1/labels/external_shipment_id/{external_shipment_id}"
    V1_LABELS_RATES_RATE_ID = "/v1/labels/rates/{rate_id}"
    V1_LABELS_SHIPMENT_SHIPMENT_ID = "/v1/labels/shipment/{shipment_id}"
    V1_LABELS_LABEL_ID = "/v1/labels/{label_id}"
    V1_LABELS_LABEL_ID_RETURN = "/v1/labels/{label_id}/return"
    V1_LABELS_LABEL_ID_TRACK = "/v1/labels/{label_id}/track"
    V1_LABELS_LABEL_ID_VOID = "/v1/labels/{label_id}/void"
    V1_MANIFESTS = "/v1/manifests"
    V1_MANIFESTS_MANIFEST_ID = "/v1/manifests/{manifest_id}"
    V1_MANIFESTS_REQUESTS_MANIFEST_REQUEST_ID = "/v1/manifests/requests/{manifest_request_id}"
    V1_PACKAGES = "/v1/packages"
    V1_PACKAGES_PACKAGE_ID = "/v1/packages/{package_id}"
    V1_PICKUPS = "/v1/pickups"
    V1_PICKUPS_PICKUP_ID = "/v1/pickups/{pickup_id}"
    V1_RATES = "/v1/rates"
    V1_RATES_BULK = "/v1/rates/bulk"
    V1_RATES_ESTIMATE = "/v1/rates/estimate"
    V1_RATES_RATE_ID = "/v1/rates/{rate_id}"
    V1_SERVICE_POINTS_LIST = "/v1/service_points/list"
    V1_SERVICE_POINTS_CARRIER_CODE_COUNTRY_CODE_SERVICE_POINT_ID = "/v1/service_points/{carrier_code}/{country_code}/{service_point_id}"
    V1_SHIPMENTS = "/v1/shipments"
    V1_SHIPMENTS_EXTERNAL_SHIPMENT_ID_EXTERNAL_SHIPMENT_ID = "/v1/shipments/external_shipment_id/{external_shipment_id}"
    V1_SHIPMENTS_RECOGNIZE = "/v1/shipments/recognize"
    V1_SHIPMENTS_SHIPMENT_ID = "/v1/shipments/{shipment_id}"
    V1_SHIPMENTS_SHIPMENT_ID_CANCEL = "/v1/shipments/{shipment_id}/cancel"
    V1_SHIPMENTS_SHIPMENT_ID_RATES = "/v1/shipments/{shipment_id}/rates"
    V1_SHIPMENTS_TAGS = "/v1/shipments/tags"
    V1_SHIPMENTS_SHIPMENT_ID_TAGS = "/v1/shipments/{shipment_id}/tags"
    V1_SHIPMENTS_SHIPMENT_ID_TAGS_TAG_NAME = "/v1/shipments/{shipment_id}/tags/{tag_name}"
    V1_TAGS = "/v1/tags"
    V1_TAGS_TAG_NAME = "/v1/tags/{tag_name}"
    V1_TAGS_TAG_NAME_NEW_TAG_NAME = "/v1/tags/{tag_name}/{new_tag_name}"
    V1_TOKENS_EPHEMERAL = "/v1/tokens/ephemeral"
    V1_TRACKING = "/v1/tracking"
    V1_TRACKING_START = "/v1/tracking/start"
    V1_TRACKING_STOP = "/v1/tracking/stop"
    V1_WAREHOUSES = "/v1/warehouses"
    V1_WAREHOUSES_WAREHOUSE_ID = "/v1/warehouses/{warehouse_id}"
    V1_WAREHOUSES_WAREHOUSE_ID_SETTINGS = "/v1/warehouses/{warehouse_id}/settings"
